### PR TITLE
wrap everything into h2o namespace

### PR DESCRIPTION
**Pull request by Evizero**
I kinda like this about the R package. This way one has to write `h2o.init(...)` etc

### CODE REVIEW

**Comment by Evizero** [comment]
[MXNet.jl](https://github.com/dmlc/MXNet.jl/blob/master/src/MXNet.jl) does something similar

**Comment by randyzwitch** [comment]
How does this differ from the current behavior? As long as you don't export anything, don't you get this same behavior?

`H2O.init()`

**Comment by Evizero** [comment]
I guess it comes down to preference. H2O is pretty short already. The difference I think is that one has to either avoid `using` (if nothing is exported) or is unable to avoid prefixing everything

**Comment by Evizero** [comment]
By the way, I don't have a strong opinion about this. I do kinda like it in MXNet, so I thought it a good enough idea to propose

**Comment by randyzwitch** [comment]
How about we hold off for now. I'm already using `h2o` as the `@pyimport` reference, but that would go away if we completely removed PyCall from the package.

I'm with you that just wrapping a Python package defeats the point of using Julia, but do you think we should excise PyCall right now, or is there an argument for getting all the basic functionality in place using PyCall, then go back and take out individual pieces? 

By wrapping using PyCall, we define all the function signatures right away. But if we could parse the Python documentation somehow, then we could just fill the function signatures with the API code.

**Comment by Evizero** [comment]
I would suggest starting small, but starting without PyCall. Maybe at first we expect the jar file to be running separately to somewhat avoid the local instance problem.

I mean if you want to start using PyCall then I'm also ok with it. I just avoid it because PyCall and the python h2o package are giving me troubles and it will probably be a while until I take the time to look into that.

**Comment by randyzwitch** [comment]
We might as well yank it out and start without it (I've spent less than 2 hours total on all the code in this repo). I just forked master into a PyCall branch if we decide we want to go back.

I'm going to close this, let's create an actual issue on how to proceed.

**Pull request closed without merging**
